version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=mydb
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongodb

  express-app:
    build: .
    container_name: express-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - DB_URL=mongodb://admin:admin@mongodb:27017/mydb?authSource=admin
